# Site Settings
title: CP&G
tagline: Research Lab
email: giovanni.travaglino@rhul.ac.uk
description: >
  The research page of the Cultural Processes & Groups Research Lab at Royal Holloway, University of Kent. Research on organized crime, political behavior and culture
baseurl: ""
url: "https://gatravaglino.github.io/"
permalink: pretty
favicon: /favicon.png
#gh_sponsor: chrisrhymes

paginate: 4
paginate_path: "/notebook/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: cpg-uni


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: UA-163960184-1

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "G.A. Travaglino"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
